---
- name: Install Kubernetes dependencies
  hosts: kube
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a
      ignore_errors: true

    - name: Remove swap entries from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^[^#].*swap'
        state: absent

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Configure sysctl for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Install CRI-O packages
      pacman:
        name:
          - cri-o
          - crictl
        state: present

    - name: Enable and start CRI-O
      systemd:
        name: crio
        enabled: yes
        state: started

    - name: Install Kubernetes packages
      pacman:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes

    - name: Hold Kubernetes packages
      command: pacman -D --asexplicit kubelet kubeadm kubectl
