---
- name: Join additional control plane nodes to cluster (HA)
  hosts: main
  become: true
  tasks:
    - name: Fetch join command for control plane from first master
      slurp:
        src: /tmp/join-command.sh
      register: join_script
      run_once: true

    - name: Extract join command
      set_fact:
        join_command: "{{ (join_script.content | b64decode | regex_replace('#!/bin/bash\\n', '')).strip() }}"

    - name: Join control plane node to cluster
      command: "{{ join_command }} --control-plane --cri-socket unix:///var/run/crio/crio.sock"
      register: join_result
      retries: 3
      delay: 10
      until: join_result.rc == 0
