---
- name: Install Flannel CNI
  hosts: kube_admin
  become: true
  vars:
    pod_cidr: "10.244.0.0/16"
  tasks:
    - name: Install helm (Arch)
      pacman:
        name: helm
        state: present
      when: ansible_os_family == 'Archlinux'

    - name: Install helm prerequisites (RPM/Deb)
      package:
        name:
          - curl
          - tar
        state: present
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Download helm install script (RPM/Deb)
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0700'
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Install helm (RPM/Deb)
      command: /tmp/get-helm-3
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Create kube-flannel namespace
      command: kubectl create namespace kube-flannel
      register: ns_create
      changed_when: "'already exists' not in ns_create.stderr"
      failed_when: ns_create.rc != 0 and 'AlreadyExists' not in ns_create.stderr

    - name: Label kube-flannel namespace
      command: kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged

    - name: Add Flannel repo
      command: helm repo add flannel https://flannel-io.github.io/flannel/
      register: helm_repo_add
      failed_when: helm_repo_add.rc != 0 and 'already exists' not in helm_repo_add.stderr

    - name: Update helm repos
      command: helm repo update

    - name: Install Flannel with Helm
      command: >
        helm upgrade --install flannel --set podCidr="{{ pod_cidr }}"
        --namespace kube-flannel flannel/flannel
